version: '3'
services:
  icp-hub-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4943:4943"
    volumes:
      - .:/app
      - dfx-cache:/root/.cache/dfinity
    environment:
      - DFX_NETWORK=local
    tty: true
    networks:
      - icp-network
    depends_on:
      - ipfs
    healthcheck:
      test: ["CMD", "dfx", "ping", "local"]
      interval: 30s
      timeout: 10s
      retries: 3
  ipfs:
    image: ipfs/kubo:latest
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
    volumes:
      - ipfs_data:/data/ipfs
    environment:
      - IPFS_PROFILE=server
    networks:
      - icp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/v0/version"]
      interval: 30s
      timeout: 10s
      retries: 3
volumes:
  dfx-cache:
  ipfs_data:
networks:
  icp-network:
    driver: bridge
    