
name: Deploy to ICP

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup DFINITY SDK
      uses: dfinity/sdk-action@v1
      with:
        dfx-version: 0.14.0
        
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Deploy to mainnet
      run: |
        dfx deploy --network ic
      env:
        DFX_NETWORK: ic
        WALLET_PRINCIPAL: ${{ secrets.WALLET_PRINCIPAL }}
