name: Docker
on:
  schedule:
    - cron: '36 21 * * *'
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20
        with:
          cosign-release: 'v2.2.4'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Detect project structure
        id: detect
        run: |
          # Check for Dockerfile in root
          if [ -f "Dockerfile" ]; then
            echo "context=." >> $GITHUB_ENV
            echo "dockerfile=Dockerfile" >> $GITHUB_ENV
          # Check for Dockerfile in frontend directory
          elif [ -f "frontend/Dockerfile" ]; then
            echo "context=./frontend" >> $GITHUB_ENV
            echo "dockerfile=./frontend/Dockerfile" >> $GITHUB_ENV
          # Check for Dockerfile in src directory
          elif [ -f "src/Dockerfile" ]; then
            echo "context=./src" >> $GITHUB_ENV
            echo "dockerfile=./src/Dockerfile" >> $GITHUB_ENV
          # Check for Dockerfile in docker directory
          elif [ -f "docker/Dockerfile" ]; then
            echo "context=./docker" >> $GITHUB_ENV
            echo "dockerfile=./docker/Dockerfile" >> $GITHUB_ENV
          else
            echo "Dockerfile not found in common locations"
            exit 1
          fi

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09
        with:
          context: ${{ env.context }}
          file: ${{ env.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: true
          sbom: true

      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: |
          echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
