##[debug]Evaluating condition for step: 'Install dependencies'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Install dependencies
##[debug]Loading inputs
##[debug]Loading env
Run npm ci
##[debug]/usr/bin/bash -e /home/runner/work/_temp/60e0e9e7-7065-45d8-aa8d-952d09a0cc20.sh
npm error code ENOENT
npm error syscall open
npm error path /home/runner/work/Icp_hub/Icp_hub/package.json
npm error errno -2
npm error enoent Could not read package.json: Error: ENOENT: no such file or directory, open '/home/runner/work/Icp_hub/Icp_hub/package.json'
npm error enoent This is related to npm not being able to find a file.
npm error enoent
npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2025-08-09T10_11_39_536Z-debug-0.log
Error: Process completed with ex
